version: '3.8'
services:
  add-contacts-form:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - RECEIVER_EMAIL=${RECEIVER_EMAIL:-dummy@example.com}
      - SERVICE_FQDN_ADD_CONTACTS_FORM_80=${SERVICE_FQDN_ADD_CONTACTS_FORM_80:-http://add-contacts-form.local}
    container_name: add-contacts-form-myapps-container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.add-contacts-form.rule=Host(`${SERVICE_FQDN_ADD_CONTACTS_FORM_80:-add-contacts-form.local}`)"
      - "traefik.http.routers.add-contacts-form.entryPoints=http"
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/index.html"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
networks:
  coolify:
    name: coolify
    external: true
